general.import = [ "colors.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetbrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetbrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetbrainsMono Nerd Font", style = "Italic" }
size = 12

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "F11", action = "ToggleFullscreen" }
]
